<a href="https://colab.research.google.com/github/shcrshonhs/corpus/blob/main/Code_Collocation_Analysis_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice: Collocation Analysis_2
<br>

## Step 1: Data Preparation

In [1]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [2]:
# Mount Google Drive to this Notebook instance.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
targetWord = "pretty"

In [4]:
fileDir = "drive/MyDrive/corpus/coha_2000s.txt"
fr = open(fileDir, 'r', encoding='utf-8')
contents = fr.readlines()
fr.close()

textList = []
AllWordsList = []

num = 0
for content in contents:
    content = content.replace("\n", "")
    if num < 100:
        print(content)
    textList.append(content.lower())

    words = content.lower().strip().split(" ")
    for word in words:
        AllWordsList.append(word)
    num += 1

Sentence
13048 time late 1840 s the low down riverfront side of new orleans
a pretty black eyed olive skin white woman about 30 dressed as an africamerican slave performs menial household and yard tasks
her clothing is period urban slave
in a genuine mississippi delta style she variously sings hums hollers slurs a traditional slow tempo africamerican spiritual how long watchman how long
her singing matches her work pace
it is throaty lusty fervent but remains an accompaniment to the performance of her chores
she speaks and sings in a genuine black dialect
for a moment she stops singing as she silently remembers something and moves to a musical sound in her head something german a popular dance song circa 1818 perhaps some joyous music from a long ago wedding reception now a dim scarce trace of a memory that periodically careens through the unconcious like a comet and possesses her soul
the comet disappears shift to indicate an internal moment a soliloquy
the following is actually a call and answer songchant
salome call i ask my father how long answer how long watchman how long call wellllll he do nt know how long answer how long watchman how long i ask my mother how long how long watchman how long ooooooh she do nt know how long how long watchman how long i ask my neighbor how long how long watchman how long welllll he do nt know how long how long watchman how long i ask de masta how long how long watchman how long annnnnd he do nt know how long i ask da missy how long how long watchman how long lawwwwwd she do nt know how long how long watchman how long i ask da preacha how long how long preacha how long ooooooh he do nt know how long how long preacha needed can be added but mind the order of them and what they are saying
p
3 salome missy wo nt whup me taday
no sah
not taday
ah gits ebeyting done
i clean de tavern an ah haul in de liquor fore de customers commence ta comin and drinkin an carryin on
den ah goes down ta de house an make de beds wash de clothes dry de clothes cook de food hoe de weeds in da garden shuck de corn feed de dogs an de chickens collec de eggs


lawd hamercy ise tired but jesus will see me through
sings a moment jesus loves me this is i know for the bible tells me so resumes speaking jesus gim me da strenf
yes lawd
ah counts my blessin s
got a good massa
heah what ise tellin ya
massa belmonti a good man
but his missy lawd fidden ta speak ta her
reckon da lawd know what he doin
he mista terious do nt know what da lawd thinkin
yessah ise proud ta be massa s mary
ah tells folks i belongs ta massa belmonti they treats me good
got plenty feed
good warm shanty with blankets and a fireplace
get suga and molassas
plenty fatback
cornmeal
chicken on sunday
good leavin s ebey day
he a good man massa belmonti
he do nt low missy lay dat stick on mah back
massa like me plenty
yessah massa like me plenty
he tell me so when he come at night
brang me a lil gift
touch my face
bitter jealously fear dat missy ob his mek ya wuck till ya bones gits soft an den complain bout what you ai nt done
she beat ya till ya scream an de blood run warm down ya legs
she da devil
spida bitch
may she bun up in hellfire
she spiteful tawad my two chilrens my two boys
ole dried up white bitch cai nt ha no chilrens
her birthin hole stopped up with hate and spite
da lawd seen fit ta keep chilren s out her hands
she be done roll over her chilrens and smotha dem lak in da bible an den wan na cut em in half or some such
dat bitch need ta go back ta hell where she come fum
fornicate wit satan
work me till mah hands bleed an mah tongue hang out
but massa like me
dem massa s boys
mah chilrens
dem massa s boys
dat bitch cai nt git roun dat
nossah
shut her mouth wide open
bitch cai nt beat me no mo
massa bless his heart do nt low dat
ise a sho nuff woman not a bitch fum hell
dis slave woman got mo lady in long watchman how long welllllll he do nt know how long karla enters white about 30
she is passing by when she notices the singing slave woman salome
she starts to pass by but is drawn back by something in salome s voice
then she looks at her closely
salome notices and grows quiet a bit apprehensive
karla comes closer and closer to inspect salome
karla is growing noticeably excited as salome grows fearful
salome never looks into karla s eyes
always she looks down or away
p
4 karla step into the light
salome beg yo pardon maam
karla step into the light please
salome yessum but ah ai nt done nothin maam
no maam
karla i just want to look at you for a moment
you look like


but this


you have to be


my god
my god
it s you
salome oh no maam my
i can see it

### Extract sentences that contain the word "pretty".

In [5]:
wordsInCorpus = 0
targetWordText = []
AllTextWT = ""
for each in textList:
    words = each.split(" ")
    for word in words:
        wordsInCorpus += 1

    if " "+targetWord+" " in each:
        targetWordText.append(each)
        AllTextWT = AllTextWT + " " + each

AllText = AllTextWT.strip()
print(wordsInCorpus)
print(len(AllWordsList))

28132499
28132499

## Step 2: Concordance table

### Check the concordance table for sentences containing "pretty".

In [6]:
from nltk import *
retokenize = RegexpTokenizer("[\w]+")
text = Text(retokenize.tokenize(AllText))
text.concordance(targetWord)

<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:2: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_11631/243500160.py:2: SyntaxWarning: invalid escape sequence '\w'
  retokenize = RegexpTokenizer("[\w]+")

Displaying 25 of 4437 matches:
                                  a pretty black eyed olive skin white woman a
enial household and yard tasks more pretty gifts and pretty trinkets for my pr
nd yard tasks more pretty gifts and pretty trinkets for my pretty daughter and
ty gifts and pretty trinkets for my pretty daughter and our pretty nannerl on
kets for my pretty daughter and our pretty nannerl on the verge of blossoming
nnerl on the verge of blossoming so pretty in springtime it is still pretty re
so pretty in springtime it is still pretty remarkable oh what a pretty young m
s still pretty remarkable oh what a pretty young maid mozart oh i m pretty goo
t a pretty young maid mozart oh i m pretty good at keeping secrets can i see t
od at keeping secrets can i see the pretty things how pretty you looked on you
ets can i see the pretty things how pretty you looked on your sixteenth birthd
y and then i bought mom a perfectly pretty blank card and then i bought myself
 it in a drawer anyway we both have pretty big roles hers is the biggest of co
am in your coffee sons of africa or pretty soon you ll be having milk looking
 soon you ll be having milk looking pretty good pero ese viejo you got pretty
 pretty good pero ese viejo you got pretty eyes papabuelo josampeacute the tob
apabuelo josampeacute the tobacco s pretty good and that s pretty much what i
he tobacco s pretty good and that s pretty much what i told them tv folks and
 what i told them tv folks and it s pretty much live and let live well it s pr
ty much live and let live well it s pretty clear that we do grow children like
the arraignment and my response was pretty catatonic not sleeping not eating r
g not eating reggie fluty it d look pretty funny i just remember russ was laug
s laughing at first but then he got pretty scared aaron mckinney uh i really d
 on to me and stuff like that i get pretty aggravated trofimov that was pretty
pretty aggravated trofimov that was pretty tactless rob bob that s pretty cold

## Step 3: Create a contingency table

### Calculate co-occurrence frequencies and individual word frequencies.

In [7]:
wordType = set()
for each in targetWordText:
    eachSplit = each.split(" ")
    for i in range(0,len(eachSplit)):
      if eachSplit[i] == targetWord and i != len(eachSplit)-1:
        wordType.add(eachSplit[i+1])
wordList = list(wordType)

print(wordList[0:10])
print(len(wordType))

['buxom', 'trained', 'goddamn', 'rifle', 'pastorale', 'recently', 'jesuitically', 'fing', 'salesgirl', 'downtoearth']
1122

### Calculate co-occurrence frequencies and filter words with a minimum frequency of 1.

In [8]:
wordFreqDict = {}
for each in wordList:
    wordFreqDict[each] = 0

for each in targetWordText:
    eachSplit = each.split(" ")
    for i in range(0,len(eachSplit)):
      if eachSplit[i] == targetWord and i != len(eachSplit)-1:
        wordFreqDict[eachSplit[i+1]] = wordFreqDict.get(eachSplit[i+1]) + 1

wordFreqDicSorted = dict(sorted(wordFreqDict.items(), key=lambda x: x[1], reverse=True))

CoOccurringWords = []
collocations = []

topNum = 0
for key, value in wordFreqDicSorted.items():
  if topNum < 30:
    if value > 1:
        CoOccurringWords.append(key)
        collocations.append(value)
        print(key, value)
  topNum += 1

print(len(CoOccurringWords))
print(CoOccurringWords[0:10])
print(collocations[0:10])

much 564
good 423
sure 170
well 124
soon 73
and 54
face 54
girl 50
young 47
little 45
but 43
hard 42
bad 41
woman 39
as 38
cool 37
boy 36
close 34
big 34
clear 33
damn 29
in 28
with 26
quickly 26
she 25
easy 22
enough 20
girls 20
nice 19
darn 19
30
['much', 'good', 'sure', 'well', 'soon', 'and', 'face', 'girl', 'young', 'little']
[564, 423, 170, 124, 73, 54, 54, 50, 47, 45]

### Calculate individual frequencies of co-occurring words.

In [9]:
CoOccurringWordsFreqDict = {}
for each in CoOccurringWords:
    CoOccurringWordsFreqDict[each] = AllWordsList.count(each)
    print(each, AllWordsList.count(each))

much 24038
good 24776
sure 10919
well 23210
soon 6360
and 728095
face 16348
girl 7763
young 11286
little 23422
but 135698
hard 10036
bad 7100
woman 12952
as 168561
cool 3127
boy 7316
close 7370
big 14018
clear 5005
damn 2107
in 461478
with 192584
quickly 4493
she 179839
easy 4526
enough 13784
girls 4441
nice 3491
darn 120

In [10]:
freqCoWord = []
freqTargetWord = []
targetword = []
wordsInCorpusList = []
targetwordCount = AllWordsList.count(targetWord)

for key, value in CoOccurringWordsFreqDict.items():
    freqCoWord.append(value)
    freqTargetWord.append(targetwordCount)
    targetword.append(targetWord)
    wordsInCorpusList.append(wordsInCorpus)

print(freqCoWord[0:10])

[24038, 24776, 10919, 23210, 6360, 728095, 16348, 7763, 11286, 23422]

### Generate the final dataset.

In [11]:
import pandas as pd
collocationTable = pd.DataFrame({'Target word':targetword,'Co-occurring words':CoOccurringWords,'Collocations':collocations,'Freq co-occurring word':freqCoWord,'Freq target word':freqTargetWord,'Words in corpus':wordsInCorpusList})
print(collocationTable)

   Target word Co-occurring words  Collocations  Freq co-occurring word  \
0       pretty               much           564                   24038
1       pretty               good           423                   24776
2       pretty               sure           170                   10919
3       pretty               well           124                   23210
4       pretty               soon            73                    6360
5       pretty                and            54                  728095
6       pretty               face            54                   16348
7       pretty               girl            50                    7763
8       pretty              young            47                   11286
9       pretty             little            45                   23422
10      pretty                but            43                  135698
11      pretty               hard            42                   10036
12      pretty                bad            41                    7100
13      pretty              woman            39                   12952
14      pretty                 as            38                  168561
15      pretty               cool            37                    3127
16      pretty                boy            36                    7316
17      pretty              close            34                    7370
18      pretty                big            34                   14018
19      pretty              clear            33                    5005
20      pretty               damn            29                    2107
21      pretty                 in            28                  461478
22      pretty               with            26                  192584
23      pretty            quickly            26                    4493
24      pretty                she            25                  179839
25      pretty               easy            22                    4526
26      pretty             enough            20                   13784
27      pretty              girls            20                    4441
28      pretty               nice            19                    3491
29      pretty               darn            19                     120

    Freq target word  Words in corpus
0               4854         28132499
1               4854         28132499
2               4854         28132499
3               4854         28132499
4               4854         28132499
5               4854         28132499
6               4854         28132499
7               4854         28132499
8               4854         28132499
9               4854         28132499
10              4854         28132499
11              4854         28132499
12              4854         28132499
13              4854         28132499
14              4854         28132499
15              4854         28132499
16              4854         28132499
17              4854         28132499
18              4854         28132499
19              4854         28132499
20              4854         28132499
21              4854         28132499
22              4854         28132499
23              4854         28132499
24              4854         28132499
25              4854         28132499
26              4854         28132499
27              4854         28132499
28              4854         28132499
29              4854         28132499

In [12]:
collocationTable[0:30]

,Target word,Co-occurring words,Collocations,Freq co-occurring word,Freq target word,Words in corpus
0,pretty,much,564,24038,4854,28132499
1,pretty,good,423,24776,4854,28132499
2,pretty,sure,170,10919,4854,28132499
3,pretty,well,124,23210,4854,28132499
4,pretty,soon,73,6360,4854,28132499
5,pretty,and,54,728095,4854,28132499
6,pretty,face,54,16348,4854,28132499
7,pretty,girl,50,7763,4854,28132499
8,pretty,young,47,11286,4854,28132499
9,pretty,little,45,23422,4854,28132499
10,pretty,but,43,135698,4854,28132499
11,pretty,hard,42,10036,4854,28132499
12,pretty,bad,41,7100,4854,28132499
13,pretty,woman,39,12952,4854,28132499
14,pretty,as,38,168561,4854,28132499
15,pretty,cool,37,3127,4854,28132499
16,pretty,boy,36,7316,4854,28132499
17,pretty,close,34,7370,4854,28132499
18,pretty,big,34,14018,4854,28132499
19,pretty,clear,33,5005,4854,28132499
20,pretty,damn,29,2107,4854,28132499
21,pretty,in,28,461478,4854,28132499
22,pretty,with,26,192584,4854,28132499
23,pretty,quickly,26,4493,4854,28132499
24,pretty,she,25,179839,4854,28132499
25,pretty,easy,22,4526,4854,28132499
26,pretty,enough,20,13784,4854,28132499
27,pretty,girls,20,4441,4854,28132499
28,pretty,nice,19,3491,4854,28132499
29,pretty,darn,19,120,4854,28132499

## Step 4: Collocation measures
**Objective**: Apply the learned collocation measures to the dataset.

### Expected Frequency
The formula for Expected Frequency is:

$$E = \frac{f(w_1) \cdot f(w_2)}{N}$$

Where:
- $f(w_1)$: Frequency of the target word.
- $f(w_2)$: Frequency of the co-occurring word.
- $N$: Total number of tokens in the corpus.

In [13]:
collocationTable['ExpectedFreq'] = (collocationTable['Freq target word']*collocationTable['Freq co-occurring word'])/collocationTable['Words in corpus']

In [14]:
collocationTable[0:30]

,Target word,Co-occurring words,Collocations,Freq co-occurring word,Freq target word,Words in corpus,ExpectedFreq
0,pretty,much,564,24038,4854,28132499,4.147532
1,pretty,good,423,24776,4854,28132499,4.274867
2,pretty,sure,170,10919,4854,28132499,1.883971
3,pretty,well,124,23210,4854,28132499,4.004669
4,pretty,soon,73,6360,4854,28132499,1.097359
5,pretty,and,54,728095,4854,28132499,125.625993
6,pretty,face,54,16348,4854,28132499,2.820695
7,pretty,girl,50,7763,4854,28132499,1.339433
8,pretty,young,47,11286,4854,28132499,1.947294
9,pretty,little,45,23422,4854,28132499,4.041247
10,pretty,but,43,135698,4854,28132499,23.413423
11,pretty,hard,42,10036,4854,28132499,1.731618
12,pretty,bad,41,7100,4854,28132499,1.225039
13,pretty,woman,39,12952,4854,28132499,2.234747
14,pretty,as,38,168561,4854,28132499,29.083627
15,pretty,cool,37,3127,4854,28132499,0.539535
16,pretty,boy,36,7316,4854,28132499,1.262307
17,pretty,close,34,7370,4854,28132499,1.271625
18,pretty,big,34,14018,4854,28132499,2.418675
19,pretty,clear,33,5005,4854,28132499,0.863566
20,pretty,damn,29,2107,4854,28132499,0.363543
21,pretty,in,28,461478,4854,28132499,79.623720
22,pretty,with,26,192584,4854,28132499,33.228571
23,pretty,quickly,26,4493,4854,28132499,0.775225
24,pretty,she,25,179839,4854,28132499,31.029540
25,pretty,easy,22,4526,4854,28132499,0.780919
26,pretty,enough,20,13784,4854,28132499,2.378300
27,pretty,girls,20,4441,4854,28132499,0.766253
28,pretty,nice,19,3491,4854,28132499,0.602339
29,pretty,darn,19,120,4854,28132499,0.020705

In [15]:
collocationTable.sort_values(by='ExpectedFreq', ascending=False)[0:30]

,Target word,Co-occurring words,Collocations,Freq co-occurring word,Freq target word,Words in corpus,ExpectedFreq
5,pretty,and,54,728095,4854,28132499,125.625993
21,pretty,in,28,461478,4854,28132499,79.623720
22,pretty,with,26,192584,4854,28132499,33.228571
24,pretty,she,25,179839,4854,28132499,31.029540
14,pretty,as,38,168561,4854,28132499,29.083627
10,pretty,but,43,135698,4854,28132499,23.413423
1,pretty,good,423,24776,4854,28132499,4.274867
0,pretty,much,564,24038,4854,28132499,4.147532
9,pretty,little,45,23422,4854,28132499,4.041247
3,pretty,well,124,23210,4854,28132499,4.004669
6,pretty,face,54,16348,4854,28132499,2.820695
18,pretty,big,34,14018,4854,28132499,2.418675
26,pretty,enough,20,13784,4854,28132499,2.378300
13,pretty,woman,39,12952,4854,28132499,2.234747
8,pretty,young,47,11286,4854,28132499,1.947294
2,pretty,sure,170,10919,4854,28132499,1.883971
11,pretty,hard,42,10036,4854,28132499,1.731618
7,pretty,girl,50,7763,4854,28132499,1.339433
17,pretty,close,34,7370,4854,28132499,1.271625
16,pretty,boy,36,7316,4854,28132499,1.262307
12,pretty,bad,41,7100,4854,28132499,1.225039
4,pretty,soon,73,6360,4854,28132499,1.097359
19,pretty,clear,33,5005,4854,28132499,0.863566
25,pretty,easy,22,4526,4854,28132499,0.780919
23,pretty,quickly,26,4493,4854,28132499,0.775225
27,pretty,girls,20,4441,4854,28132499,0.766253
28,pretty,nice,19,3491,4854,28132499,0.602339
15,pretty,cool,37,3127,4854,28132499,0.539535
20,pretty,damn,29,2107,4854,28132499,0.363543
29,pretty,darn,19,120,4854,28132499,0.020705

In [16]:
collocationTable['OF-EF'] = collocationTable['Collocations']-collocationTable['ExpectedFreq']

In [17]:
collocationTable.sort_values(by='OF-EF', ascending=False)[0:30]

,Target word,Co-occurring words,Collocations,Freq co-occurring word,Freq target word,Words in corpus,ExpectedFreq,OF-EF
0,pretty,much,564,24038,4854,28132499,4.147532,559.852468
1,pretty,good,423,24776,4854,28132499,4.274867,418.725133
2,pretty,sure,170,10919,4854,28132499,1.883971,168.116029
3,pretty,well,124,23210,4854,28132499,4.004669,119.995331
4,pretty,soon,73,6360,4854,28132499,1.097359,71.902641
6,pretty,face,54,16348,4854,28132499,2.820695,51.179305
7,pretty,girl,50,7763,4854,28132499,1.339433,48.660567
8,pretty,young,47,11286,4854,28132499,1.947294,45.052706
9,pretty,little,45,23422,4854,28132499,4.041247,40.958753
11,pretty,hard,42,10036,4854,28132499,1.731618,40.268382
12,pretty,bad,41,7100,4854,28132499,1.225039,39.774961
13,pretty,woman,39,12952,4854,28132499,2.234747,36.765253
15,pretty,cool,37,3127,4854,28132499,0.539535,36.460465
16,pretty,boy,36,7316,4854,28132499,1.262307,34.737693
17,pretty,close,34,7370,4854,28132499,1.271625,32.728375
19,pretty,clear,33,5005,4854,28132499,0.863566,32.136434
18,pretty,big,34,14018,4854,28132499,2.418675,31.581325
20,pretty,damn,29,2107,4854,28132499,0.363543,28.636457
23,pretty,quickly,26,4493,4854,28132499,0.775225,25.224775
25,pretty,easy,22,4526,4854,28132499,0.780919,21.219081
10,pretty,but,43,135698,4854,28132499,23.413423,19.586577
27,pretty,girls,20,4441,4854,28132499,0.766253,19.233747
29,pretty,darn,19,120,4854,28132499,0.020705,18.979295
28,pretty,nice,19,3491,4854,28132499,0.602339,18.397661
26,pretty,enough,20,13784,4854,28132499,2.378300,17.621700
14,pretty,as,38,168561,4854,28132499,29.083627,8.916373
24,pretty,she,25,179839,4854,28132499,31.029540,-6.029540
22,pretty,with,26,192584,4854,28132499,33.228571,-7.228571
21,pretty,in,28,461478,4854,28132499,79.623720,-51.623720
5,pretty,and,54,728095,4854,28132499,125.625993,-71.625993

### T-Score
The formula for T-Score is:

$$T = \frac{f(w_1, w_2) - E}{\sqrt{f(w_1, w_2)}}$$

Where:
- $f(w_1, w_2)$: Observed frequency of the collocation.
즉, 관찰빈도
- $E$: Expected frequency.

In [18]:
import numpy as np
collocationTable['T-score'] = (collocationTable['Collocations'] - collocationTable['ExpectedFreq'])/np.sqrt(collocationTable['Collocations'])
collocationTable.sort_values(by='T-score', ascending=False)[0:30]

,Target word,Co-occurring words,Collocations,Freq co-occurring word,Freq target word,Words in corpus,ExpectedFreq,OF-EF,T-score
0,pretty,much,564,24038,4854,28132499,4.147532,559.852468,23.574042
1,pretty,good,423,24776,4854,28132499,4.274867,418.725133,20.359113
2,pretty,sure,170,10919,4854,28132499,1.883971,168.116029,12.893911
3,pretty,well,124,23210,4854,28132499,4.004669,119.995331,10.775899
4,pretty,soon,73,6360,4854,28132499,1.097359,71.902641,8.415568
6,pretty,face,54,16348,4854,28132499,2.820695,51.179305,6.964621
7,pretty,girl,50,7763,4854,28132499,1.339433,48.660567,6.881643
8,pretty,young,47,11286,4854,28132499,1.947294,45.052706,6.571613
11,pretty,hard,42,10036,4854,28132499,1.731618,40.268382,6.213546
12,pretty,bad,41,7100,4854,28132499,1.225039,39.774961,6.211805
9,pretty,little,45,23422,4854,28132499,4.041247,40.958753,6.105770
15,pretty,cool,37,3127,4854,28132499,0.539535,36.460465,5.994064
13,pretty,woman,39,12952,4854,28132499,2.234747,36.765253,5.887152
16,pretty,boy,36,7316,4854,28132499,1.262307,34.737693,5.789615
17,pretty,close,34,7370,4854,28132499,1.271625,32.728375,5.612870
19,pretty,clear,33,5005,4854,28132499,0.863566,32.136434,5.594235
18,pretty,big,34,14018,4854,28132499,2.418675,31.581325,5.416153
20,pretty,damn,29,2107,4854,28132499,0.363543,28.636457,5.317657
23,pretty,quickly,26,4493,4854,28132499,0.775225,25.224775,4.946985
25,pretty,easy,22,4526,4854,28132499,0.780919,21.219081,4.523923
29,pretty,darn,19,120,4854,28132499,0.020705,18.979295,4.354149
27,pretty,girls,20,4441,4854,28132499,0.766253,19.233747,4.300797
28,pretty,nice,19,3491,4854,28132499,0.602339,18.397661,4.220713
26,pretty,enough,20,13784,4854,28132499,2.378300,17.621700,3.940332
10,pretty,but,43,135698,4854,28132499,23.413423,19.586577,2.986925
14,pretty,as,38,168561,4854,28132499,29.083627,8.916373,1.446427
24,pretty,she,25,179839,4854,28132499,31.029540,-6.029540,-1.205908
22,pretty,with,26,192584,4854,28132499,33.228571,-7.228571,-1.417639
5,pretty,and,54,728095,4854,28132499,125.625993,-71.625993,-9.747063
21,pretty,in,28,461478,4854,28132499,79.623720,-51.623720,-9.755966

### Z-Score
The formula for Z-Score is:

$$Z = \frac{f(w_1, w_2) - E}{\sqrt{E}}$$

Where:
- $f(w_1, w_2)$: Observed frequency of the collocation.
- $E$: Expected frequency.

In [19]:
import numpy as np
collocationTable['Z-score'] = (collocationTable['Collocations'] - collocationTable['ExpectedFreq'])/np.sqrt(collocationTable['ExpectedFreq'])
collocationTable.sort_values(by='Z-score', ascending=False)[0:30]

,Target word,Co-occurring words,Collocations,Freq co-occurring word,Freq target word,Words in corpus,ExpectedFreq,OF-EF,T-score,Z-score
0,pretty,much,564,24038,4854,28132499,4.147532,559.852468,23.574042,274.902508
1,pretty,good,423,24776,4854,28132499,4.274867,418.725133,20.359113,202.519899
29,pretty,darn,19,120,4854,28132499,0.020705,18.979295,4.354149,131.899675
2,pretty,sure,170,10919,4854,28132499,1.883971,168.116029,12.893911,122.481912
4,pretty,soon,73,6360,4854,28132499,1.097359,71.902641,8.415568,68.638938
3,pretty,well,124,23210,4854,28132499,4.004669,119.995331,10.775899,59.962682
15,pretty,cool,37,3127,4854,28132499,0.539535,36.460465,5.994064,49.637801
20,pretty,damn,29,2107,4854,28132499,0.363543,28.636457,5.317657,47.494277
7,pretty,girl,50,7763,4854,28132499,1.339433,48.660567,6.881643,42.045221
12,pretty,bad,41,7100,4854,28132499,1.225039,39.774961,6.211805,35.936424
19,pretty,clear,33,5005,4854,28132499,0.863566,32.136434,5.594235,34.581985
8,pretty,young,47,11286,4854,28132499,1.947294,45.052706,6.571613,32.285323
16,pretty,boy,36,7316,4854,28132499,1.262307,34.737693,5.789615,30.918498
11,pretty,hard,42,10036,4854,28132499,1.731618,40.268382,6.213546,30.601176
6,pretty,face,54,16348,4854,28132499,2.820695,51.179305,6.964621,30.473079
17,pretty,close,34,7370,4854,28132499,1.271625,32.728375,5.612870,29.023179
23,pretty,quickly,26,4493,4854,28132499,0.775225,25.224775,4.946985,28.649257
13,pretty,woman,39,12952,4854,28132499,2.234747,36.765253,5.887152,24.593674
25,pretty,easy,22,4526,4854,28132499,0.780919,21.219081,4.523923,24.011736
28,pretty,nice,19,3491,4854,28132499,0.602339,18.397661,4.220713,23.705108
27,pretty,girls,20,4441,4854,28132499,0.766253,19.233747,4.300797,21.972414
9,pretty,little,45,23422,4854,28132499,4.041247,40.958753,6.105770,20.374596
18,pretty,big,34,14018,4854,28132499,2.418675,31.581325,5.416153,20.306805
26,pretty,enough,20,13784,4854,28132499,2.378300,17.621700,3.940332,11.426532
10,pretty,but,43,135698,4854,28132499,23.413423,19.586577,2.986925,4.047866
14,pretty,as,38,168561,4854,28132499,29.083627,8.916373,1.446427,1.653347
24,pretty,she,25,179839,4854,28132499,31.029540,-6.029540,-1.205908,-1.082422
22,pretty,with,26,192584,4854,28132499,33.228571,-7.228571,-1.417639,-1.253997
21,pretty,in,28,461478,4854,28132499,79.623720,-51.623720,-9.755966,-5.785329
5,pretty,and,54,728095,4854,28132499,125.625993,-71.625993,-9.747063,-6.390442

### Mutual Information (MI)
The formula for Mutual Information is:

$$MI = \log_2\left(\frac{f(w_1, w_2)}{N} \bigg/ \left(\frac{f(w_1)}{N} \cdot \frac{f(w_2)}{N}\right)\right)$$

Where:
- $f(w_1)$: Frequency of the target word.
- $f(w_2)$: Frequency of the co-occurring word.
- $N$: Total number of tokens in the corpus.
- $f(w_1, w_2)$: Observed frequency of the collocation.

In [20]:
import numpy as np
collocationTable['MI'] = np.log2((collocationTable['Collocations']/collocationTable['Words in corpus'])/((collocationTable['Freq target word']/collocationTable['Words in corpus'])*(collocationTable['Freq co-occurring word']/collocationTable['Words in corpus'])))
collocationTable.sort_values(by='MI', ascending=False)[0:30]

,Target word,Co-occurring words,Collocations,Freq co-occurring word,Freq target word,Words in corpus,ExpectedFreq,OF-EF,T-score,Z-score,MI
29,pretty,darn,19,120,4854,28132499,0.020705,18.979295,4.354149,131.899675,9.841813
0,pretty,much,564,24038,4854,28132499,4.147532,559.852468,23.574042,274.902508,7.087298
1,pretty,good,423,24776,4854,28132499,4.274867,418.725133,20.359113,202.519899,6.628634
2,pretty,sure,170,10919,4854,28132499,1.883971,168.116029,12.893911,122.481912,6.495614
20,pretty,damn,29,2107,4854,28132499,0.363543,28.636457,5.317657,47.494277,6.317782
15,pretty,cool,37,3127,4854,28132499,0.539535,36.460465,5.994064,49.637801,6.099666
4,pretty,soon,73,6360,4854,28132499,1.097359,71.902641,8.415568,68.638938,6.055789
19,pretty,clear,33,5005,4854,28132499,0.863566,32.136434,5.594235,34.581985,5.256016
7,pretty,girl,50,7763,4854,28132499,1.339433,48.660567,6.881643,42.045221,5.222234
23,pretty,quickly,26,4493,4854,28132499,0.775225,25.224775,4.946985,28.649257,5.067752
12,pretty,bad,41,7100,4854,28132499,1.225039,39.774961,6.211805,35.936424,5.064725
28,pretty,nice,19,3491,4854,28132499,0.602339,18.397661,4.220713,23.705108,4.979279
3,pretty,well,124,23210,4854,28132499,4.004669,119.995331,10.775899,59.962682,4.952513
16,pretty,boy,36,7316,4854,28132499,1.262307,34.737693,5.789615,30.918498,4.833862
25,pretty,easy,22,4526,4854,28132499,0.780919,21.219081,4.523923,24.011736,4.816187
17,pretty,close,34,7370,4854,28132499,1.271625,32.728375,5.612870,29.023179,4.740790
27,pretty,girls,20,4441,4854,28132499,0.766253,19.233747,4.300797,21.972414,4.706035
11,pretty,hard,42,10036,4854,28132499,1.731618,40.268382,6.213546,30.601176,4.600197
8,pretty,young,47,11286,4854,28132499,1.947294,45.052706,6.571613,32.285323,4.593118
6,pretty,face,54,16348,4854,28132499,2.820695,51.179305,6.964621,30.473079,4.258837
13,pretty,woman,39,12952,4854,28132499,2.234747,36.765253,5.887152,24.593674,4.125291
18,pretty,big,34,14018,4854,28132499,2.418675,31.581325,5.416153,20.306805,3.813246
9,pretty,little,45,23422,4854,28132499,4.041247,40.958753,6.105770,20.374596,3.477052
26,pretty,enough,20,13784,4854,28132499,2.378300,17.621700,3.940332,11.426532,3.071997
10,pretty,but,43,135698,4854,28132499,23.413423,19.586577,2.986925,4.047866,0.877001
14,pretty,as,38,168561,4854,28132499,29.083627,8.916373,1.446427,1.653347,0.385792
24,pretty,she,25,179839,4854,28132499,31.029540,-6.029540,-1.205908,-1.082422,-0.311714
22,pretty,with,26,192584,4854,28132499,33.228571,-7.228571,-1.417639,-1.253997,-0.353913
5,pretty,and,54,728095,4854,28132499,125.625993,-71.625993,-9.747063,-6.390442,-1.218104
21,pretty,in,28,461478,4854,28132499,79.623720,-51.623720,-9.755966,-5.785329,-1.507771

### Log-Likelihood (LL)
The formula for Log-Likelihood is:

$$LL = 2 \cdot \sum \left(O \cdot \log\left(\frac{O}{E}\right)\right)$$

Where:
- $O$: Observed frequency.
- $E$: Expected frequency.

For collocation analysis, the expanded formula is:

$$LL = 2 \cdot \left(O_{11} \cdot \log\left(\frac{O_{11}}{E_{11}}\right) + O_{12} \cdot \log\left(\frac{O_{12}}{E_{12}}\right) + O_{21} \cdot \log\left(\frac{O_{21}}{E_{21}}\right) + O_{22} \cdot \log\left(\frac{O_{22}}{E_{22}}\right)\right)$$

Where:
- $O_{11}$: Observed frequency of the collocation.
- $O_{12}$: Observed frequency of the target word without the collocate.
- $O_{21}$: Observed frequency of the collocate without the target word.
- $O_{22}$: Observed frequency of all other words.
- $E_{11}, E_{12}, E_{21}, E_{22}$: Corresponding expected frequencies.

In [21]:
def loglikelihood(score1, score2, score3, score4):
    outList = []
    for i in range(0,len(score1)):
        import math
        result = 2 * (
        score1[i] * math.log(score1[i], math.e) +
        score2[i] * math.log(score2[i], math.e) +
        score3[i] * math.log(score3[i], math.e) +
        score4[i] * math.log(score4[i], math.e) -
        (score1[i] + score2[i]) * math.log(score1[i] + score2[i], math.e) -
        (score1[i] + score3[i]) * math.log(score1[i] + score3[i], math.e) -
        (score2[i] + score4[i]) * math.log(score2[i] + score4[i], math.e) -
        (score3[i] + score4[i]) * math.log(score3[i] + score4[i], math.e) +
        (score1[i] + score2[i] + score3[i] + score4[i]) * math.log(score1[i] + score2[i] + score3[i] + score4[i], math.e))

        outList.append(result)
    return outList

In [22]:
collocationTable['LL'] = loglikelihood(collocationTable['Collocations'],(collocationTable['Freq target word']-collocationTable['Collocations']),(collocationTable['Freq co-occurring word']-collocationTable['Collocations']),(collocationTable['Words in corpus']-collocationTable['Freq target word'])-(collocationTable['Freq co-occurring word']-collocationTable['Collocations']))
collocationTable.sort_values(by='LL', ascending=False)[0:30]

,Target word,Co-occurring words,Collocations,Freq co-occurring word,Freq target word,Words in corpus,ExpectedFreq,OF-EF,T-score,Z-score,MI,LL
0,pretty,much,564,24038,4854,28132499,4.147532,559.852468,23.574042,274.902508,7.087298,4502.064777
1,pretty,good,423,24776,4854,28132499,4.274867,418.725133,20.359113,202.519899,6.628634,3093.962375
2,pretty,sure,170,10919,4854,28132499,1.883971,168.116029,12.893911,122.481912,6.495614,1203.086130
3,pretty,well,124,23210,4854,28132499,4.004669,119.995331,10.775899,59.962682,4.952513,614.964571
4,pretty,soon,73,6360,4854,28132499,1.097359,71.902641,8.415568,68.638938,6.055789,470.924453
7,pretty,girl,50,7763,4854,28132499,1.339433,48.660567,6.881643,42.045221,5.222234,265.451898
15,pretty,cool,37,3127,4854,28132499,0.539535,36.460465,5.994064,49.637801,6.099666,240.650064
29,pretty,darn,19,120,4854,28132499,0.020705,18.979295,4.354149,131.899675,9.841813,224.519533
6,pretty,face,54,16348,4854,28132499,2.820695,51.179305,6.964621,30.473079,4.258837,217.159834
8,pretty,young,47,11286,4854,28132499,1.947294,45.052706,6.571613,32.285323,4.593118,209.762857
12,pretty,bad,41,7100,4854,28132499,1.225039,39.774961,6.211805,35.936424,5.064725,208.869486
20,pretty,damn,29,2107,4854,28132499,0.363543,28.636457,5.317657,47.494277,6.317782,197.278324
11,pretty,hard,42,10036,4854,28132499,1.731618,40.268382,6.213546,30.601176,4.600197,187.803742
19,pretty,clear,33,5005,4854,28132499,0.863566,32.136434,5.594235,34.581985,5.256016,176.597968
16,pretty,boy,36,7316,4854,28132499,1.262307,34.737693,5.789615,30.918498,4.833862,172.180733
17,pretty,close,34,7370,4854,28132499,1.271625,32.728375,5.612870,29.023179,4.740790,158.362527
13,pretty,woman,39,12952,4854,28132499,2.234747,36.765253,5.887152,24.593674,4.125291,149.889157
9,pretty,little,45,23422,4854,28132499,4.041247,40.958753,6.105770,20.374596,3.477052,135.410934
23,pretty,quickly,26,4493,4854,28132499,0.775225,25.224775,4.946985,28.649257,5.067752,132.484025
18,pretty,big,34,14018,4854,28132499,2.418675,31.581325,5.416153,20.306805,3.813246,116.848191
25,pretty,easy,22,4526,4854,28132499,0.780919,21.219081,4.523923,24.011736,4.816187,104.640772
28,pretty,nice,19,3491,4854,28132499,0.602339,18.397661,4.220713,23.705108,4.979279,94.523840
27,pretty,girls,20,4441,4854,28132499,0.766253,19.233747,4.300797,21.972414,4.706035,92.171282
5,pretty,and,54,728095,4854,28132499,125.625993,-71.625993,-9.747063,-6.390442,-1.218104,53.151668
26,pretty,enough,20,13784,4854,28132499,2.378300,17.621700,3.940332,11.426532,3.071997,50.017080
21,pretty,in,28,461478,4854,28132499,79.623720,-51.623720,-9.755966,-5.785329,-1.507771,45.283479
10,pretty,but,43,135698,4854,28132499,23.413423,19.586577,2.986925,4.047866,0.877001,13.187807
14,pretty,as,38,168561,4854,28132499,29.083627,8.916373,1.446427,1.653347,0.385792,2.507436
22,pretty,with,26,192584,4854,28132499,33.228571,-7.228571,-1.417639,-1.253997,-0.353913,1.711944
24,pretty,she,25,179839,4854,28132499,31.029540,-6.029540,-1.205908,-1.082422,-0.311714,1.263627